// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hhrwbzxbpzxoesbrszbw.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocndienhicHp4b2VzYnJzemJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4MTA3NzksImV4cCI6MjA0ODM4Njc3OX0.NgDUAWyluvwYqalKaVuP558HLzxXPab3R0feZdzt3wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);